name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'oracle'

    - name: Build jar with Maven
      run: |
        mvn versions:set -DnewVersion=${{ github.ref_name }} -DgenerateBackupPoms=false
        mvn package

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: editeur de texte
        path: target/target/EditeurDeTexte-${{ github.ref_name }}.jar
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/EditeurDeTexte-${{ github.ref_name }}.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
